#!/bin/bash

#
# WhatsApp X Sender 
#
# @author:  Pablo Bozzolo
# @licence: GNU	
#
# TODO: 
#   
# - Intentar calcular las coordenadas en función del tamaño de la window 
#
#
# Ej de uso:
#
# xsender +5491114441088 'Estimado xxx: muchas gracias por usar nuestro xsender :)'
#

# Datos

[[ $# -lt 2 ]] && { echo 'Uso: xsender telefono mensaje'; exit 1; }
tel="$1"; msg="$2"

# Coordenadas a ser determinadas 
# (artesanalmente por ahora)

# Coordenadas dentro del cuadro de búsqueda de contactos
x='682'
y='349'

# Coordenadas dentro de la caja de texto donde se escriben los mensajes
x2='712'
y2='610'

# Existe la ventana que busco?
wm=$(wmctrl -l | grep ' WhatsApp')

# Si falla .... chau
[[ $? -ne 0 ]] && { echo "No se pudo localizar una ventana con WhatsApp";exit 1; }

echo "Enviando WhastaApp a $1 ..."

# Obtengo el id de la window
wm_id=`echo $wm | awk '{print $1};'` && \

# Me posiciono sobre la caja de búsqueda y le doy foco haciendo click
xdotool windowactivate "$wm_id" && \
xdotool mousemove $x $y sleep 0.1 click 1 && \

# Typeo tel
xdotool type "$tel"

# Me posiciono sobre el contacto seleccionado
xdotool mousemove $x2 $y2 sleep 0.1 click 1 && \

# Typeo mensaje
xdotool type "$msg"

# Envio el mensaje 
xdotool keydown KP_Enter keyup KP_Enter keydown Escape keyup Escape